### ISSUE TITLE
Handle round robin a-records properly 

### ISSUE THREAD

**Issue by fast90** [ccc-ffm/christian#45]

**Comment by chaosmaster** [comment]
What is the issue here?

**Comment by fast90** [comment]
hackint does dns round robin. For example:

dig irc.hackint.org
;; ANSWER SECTION:
irc.hackint.org.        223     IN      A       148.251.206.139
irc.hackint.org.        223     IN      A       130.83.198.4
irc.hackint.org.        223     IN      A       195.160.168.7

dig irc.hackint.org
;; ANSWER SECTION:
irc.hackint.org.        223     IN      A       130.83.198.4
irc.hackint.org.        223     IN      A       195.160.168.7
irc.hackint.org.        223     IN      A       148.251.206.139

If the connection to one of the servers fails it would be nice not to connect to the "bad" server again.

**Comment by chaosmaster** [comment]
so blacklist "bad" server for some time, or just choose server at random?
If I'm not mistaken, christian would currently choose a different server after 5 minutes (TTL= 300) because the DNS reply would have a different order?

Also with 46699ebc0e2c920fcd6f58c360a82539eac4a082 connection should be retried after a failed attempt.
